name: Windows Build

on:
  push: {}
  pull_request: {}

jobs:
  test:
    name: Run Tests
    runs-on: windows-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.0'

      - name: Check out code
        uses: actions/checkout@v4

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Build
        run: |
          go mod tidy 
          go build -o PGNHelper.exe

      - name: Clean
        run: |
          git clean -fX
