name: Label Good First Issue

on:
  issues:
    types: [opened]

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - name: Label issue
        uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: |
            Thank you for opening your first issue in this repo! We'll review it soon.
            Meanwhile, please make sure you've read the contribution guidelines and follow them.
          label: Good First Issue
