name: Label sponsors

on:
  pull_request:
    types: [opened]
  issues:
    types: [opened]

jobs:
  label:
    name: is-sponsor-label
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Add sponsor label to PRs and Issues
        uses: JasonEtco/is-sponsor-label-action@v2
        with:
          label: Sponsor 💖
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
