name: Mac

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Tests
    strategy:
      matrix:
        go-version: ['1.22.0', '1.21.5', '1.21.0']
    runs-on: macos-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Check out code
        uses: actions/checkout@v4

      - name: List directory content
        run: ls -la

      - name: Test
        run: go test ./... -v

  build:
    name: Build
    needs: test
    strategy:
      matrix:
        go-version: ['1.22.0', '1.21.5', '1.21.0']
    runs-on: macos-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Check out code
        uses: actions/checkout@v4

      - name: Build
        run: go build -o PGNHelper

      - name: Clean
        run: |
          git clean -fX
