name: Windows

on:
  push:
  pull_request:

jobs:
  test:
    name: Run Tests
    strategy:
      matrix:
        go-version: ['1.22.0', '1.21.5', '1.21.0']
    runs-on: windows-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Check out code
        uses: actions/checkout@v4

      - name: List directory content
        run: ls

      - name: Test
        run: go test ./... -v

  build:
    name: Build
    needs: test
    strategy:
      matrix:
        go-version: ['1.22.0', '1.21.5', '1.21.0']
    runs-on: windows-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Check out code
        uses: actions/checkout@v4

      - name: Build
        run: go build -o PGNHelper

      - name: Clean
        run: |
          git clean -fX

  buildtests:
    name: Buildtests
    needs: [test, build]
    strategy:
      matrix:
        go-version: ['1.22.0', '1.21.5', '1.21.0']
    runs-on: windows-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Check out code
        uses: actions/checkout@v4

      - name: Build pgn
        run: |
          go build -o pgn.exe

      - name: Switch folder
        run: |
          cp pgn.exe ./test/pgn.exe

      - name: Location and System
        working-directory: test
        run: |
          ls 
          pwd

      - name: Parse PGN to JSON with no JSON flag
        working-directory: test
        run: |
          .\pgn.exe -parsePGN parse.pgn
          ls
          type parse.json

      - name: Parse PGN to JSON with JSON Flag
        working-directory: test
        run: |
          .\pgn.exe -parsePGN parse.pgn test.json
          ls
          type test.json

      - name: Parse JSON to PGN with no PGN flag
        working-directory: test
        run: |
          .\pgn.exe -parseJSON games.json
          ls
          type games.pgn

      - name: Parse JSON to PGN with no PGN flag
        working-directory: test
        run: |
          .\pgn.exe -parseJSON games.json dummy.pgn
          ls
          type dummy.pgn
      - name: Remove Event Date in PGN
        working-directory: test
        run: |
          pgn -EventDate parse.pgn
          ls -aril          
          type parse.pgn

      - name: Remove Event Date in JSON
        working-directory: test
        run: |
          pgn -EventDate test.json
          ls           
          type test.json 

      - name: Clean
        run: |
          git clean -fX
